CUSTOM_SETTINGS = {
"CONCURRENT_REQUESTS_PER_DOMAIN": 1,
"DEPTH_LIMIT": 10,
"DOWNLOAD_DELAY": 5,
"RANDOMIZE_DOWNLOAD_DELAY": True,
"ROBOTSTXT_OBEY": False,
"USER_AGENT": "Breaking-Bot",
"AUTOTHROTTLE_ENABLED": True,
"AUTOTHROTTLE_START_DELAY": 2.0,
"AUTOTHROTTLE_TARGET_CONCURRENCY": 2.0,
"AUTOTHROTTLE_MAX_DELAY": 20,
}