CUSTOM_SETTINGS = {
"CONCURRENT_REQUESTS_PER_DOMAIN": 1,
"DEPTH_LIMIT": 10,
"DNS_TIMEOUT": 100,
"DNSCACHE_ENABLED": True,
"DOWNLOAD_DELAY": 5,
"RANDOMIZE_DOWNLOAD_DELAY": True,
"REDIRECT_MAX_TIMES": 5,
"ROBOTSTXT_OBEY": False,
"USER_AGENT": "Breaking-Bot"
}